---
- name: Prepare directories and files
  hosts: tag_docker-host
  become: true

  tasks:
    - name: daemon.json config file
      template:
        src: "../templates/daemon.json.j2"
        dest: "/etc/docker/daemon.json"
        notify: restart docker

  handlers:
    - name: restart docker
      become: true
      systemd:
        name: docker
        state: restarted
