---
- name: Prepare directories and files
  hosts: tag_registry
  become: true

  tasks:
    - name: create required directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /srv/nexus3
        - /srv/nexus3/nexus-data

    - name: copy compose-file
      copy:
        src: "../files/sonatype_nexus3.yml"
        dest: "/srv/nexus3/docker-compose.yml"
